name: CI

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        scala:
          - 2.13.5
          - 2.12.13

    steps:
      - uses: actions/checkout@v4

      - uses: coursier/cache-action@v6

      - name: setup Java 11 # TODO switch to 17
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.11

      - name: setup SBT
        uses: sbt/setup-sbt@v1

      - name: check code ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} clean check

      - name: build ${{ matrix.scala }}
        run: sbt ++${{ matrix.scala }} clean coverage test

      - name: test coverage
        if: success()
        run: sbt ++${{ matrix.scala }} coverageAggregate coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_FLAG_NAME: Scala ${{ matrix.scala }}
